is_shoppingcart_controller:
    path: /is_shoppingcart/configuration
    methods: [GET]
    defaults:
        _controller: 'Oksydan\IsShoppingcart\Controller\IsShoppingCartController::index'

is_shoppingcart_controller_configuration_save:
    path: /is_shoppingcart/configuration
    methods: [POST, PATCH]
    defaults:
        _controller: 'Oksydan\IsShoppingcart\Controller\IsShoppingCartController::saveConfiguration'
